name: flutter_pdf_flipbook
description: Display PDFs as beautiful flipbooks with smooth page-turn animations on mobile, web, and desktop.
version: 1.0.0
homepage: https://github.com/Munawer-Ali/Flutter-PDF-Flipbook
repository: https://github.com/Munawer-Ali/Flutter-PDF-Flipbook
issue_tracker: https://github.com/Munawer-Ali/Flutter-PDF-Flipbook/issues
documentation: https://github.com/Munawer-Ali/Flutter-PDF-Flipbook#readme

topics:
  - pdf
  - flipbook
  - animation
  - flutter
  - ebook

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pdfx: ^2.6.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
